### ISSUE TITLE
Support for aesXXX-gcm@openssh.com ciphers

### ISSUE THREAD

**Issue by markspeters** [hierynomus/sshj#217]
SSHJ should add support for the following ciphers:
- aes128-gcm@openssh.com
- aes256-gcm@openssh.com

I believe these ciphers are provided by the BouncyCastle and Java 8 security providers.

**Comment by kdvolder** [comment]
The server I'm trying to connect to only supports `chacha20-poly1305@openssh.com` and `aes128-gcm@openssh.com`.

So can't use SSHJ to connect to it. It would really help if sshj supported these ciphers out of the box. 

I wonder if there is a way for me to add this kind of cypher support myself? e.g. via some special configuration options?

**Comment by hierynomus** [comment]
@kdvolder Normally I'd say yes, unfortunately, the GCM ciphers and chacha20-poly1305 should be implemented as they influence how the package needs to be decoded and encoded. The packet formats are slightly different. Implementing this is something that has been on my todo list for quite some time indeed.

**Comment by kdvolder** [comment]
Thanks for the response. I'll take your word for that as I know very little about how any of these cipher's work.  Luckily for us I was able to convince someone who has control over this at the server's side to loosen up a bit and add a few more cypher's that sshj does support out of the box.

Still would be nice if sshj supported them, but at least my problem is solved for now.

**Comment by vishva-shah** [comment]
@hierynomus,
Greetings. Can you please confirm when can we expect SSHJ support for the GCM ciphers and chacha20-poly1305, out of the box?
Thanks.

**Comment by asvc** [comment]
Just a heads-up, this affects [Cyberduck](https://cyberduck.io) and [Mountain Duck](https://mountainduck.io/) as [Iterate](https://iterate.ch/) is using this implementation in both.

**Comment by TranceLove** [comment]
As a developer of [Amaze File Manager](https://github.com/TeamAmaze/AmazeFileManager) I had been using sshj to do SFTP since 2018 ;) and we have requests to add support for AES-GCM ciphers too.

I have ported Apache MINA-SSHD's AES-GCM support to sshj, after seeing their recent PR https://github.com/apache/mina-sshd/pull/132 by @jvz. It connects to OpenSSH and MINA-SSHD current master when restricting ciphers to `aes-gcm128@openssh.com` or `aes256-gcm@openssh.com`.

Let me do some more tests (as `Decoder` and `Encoder` had been modified to accommodate AES-GCM ciphers) and I will submit a PR in a few weeks away.
