### ISSUE TITLE
BouncyCastle is required to read a key of type ecdsa-sha2-nistp256

### ISSUE THREAD

**Issue by MetalCar** [hierynomus/sshj#398]
Hello all,

i need some help with this error-message:
BouncyCastle is required to read a key of type ecdsa-sha2-nistp256

The error occures when i call `connect()` on my `SSHClient`.
And the error occures only, when i'm executing the following code from inside a jar-File.

```java
SSHClient ssh = new SSHClient();
ssh.loadKnownHosts();
ssh.connect("my-hostname");
```

I hope someone knows what I have to do here.
Thanks for your help!

**Comment by hierynomus** [comment]
Add bouncy castle to your project dependencies :).

Op 29 jan. 2018 9:17 a.m. schreef "MetalCar" <notifications@github.com>:

**Comment by MetalCar** [comment]
Ok....It's to early in the morning 😆
Thanks for helping out!

**Comment by MetalCar** [comment]
@hierynomus Ok i don't get it...Should I add it to my pom.xml, because i'm using maven. Which version should i add? I'm very unexperienced with this bouncycastle thing

**Comment by hierynomus** [comment]
Hi, yes add bouncycastle 1.57 to your pom.xml indeed. Groupid=org.bouncycastle, artifactid=bcprov-jdk15on

**Comment by MetalCar** [comment]
But when i add this to my pom.xml and rebuild my jar and try again to run the jar, so the same error occures.

**Comment by hierynomus** [comment]
Don't forget to register the bouncycastle security provider...

**Comment by wdcwells** [comment]
`Security.addProvider(new BouncyCastleProvider());
        try (SSHClient ssh = new SSHClient()){
            ssh.loadKnownHosts();
            ssh.connect("localhost");`
i still got this error after what you told to do

**Comment by hierynomus** [comment]
In that case the most probable problem is that you're not running with the unlimited cryptography strength extensions loaded in your jre.

**Comment by wdcwells** [comment]
@hierynomus  this only happen on the first time trying to connect an unknown hosts
if i did it on the terminal before, this will go correctly

**Comment by hierynomus** [comment]
Hmm.. Then it might be throwing the wrong exception message when the key is not in the known-hosts file. Can you send an entire trace log?

**Comment by wdcwells** [comment]
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:55550,suspend=y,server=n -javaagent:/Users/wdc/Library/Caches/IntelliJIdea2017.3/captureAgent/debugger-agent.jar=/private/var/folders/7b/b0kp96h50x91hq3p9hwzvh4h0000gn/T/capture275.props -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/tools.jar:/Users/wdc/Develop/WorkSpace/IdeaProjects/GitHub/learning/test/target/classes:/Users/wdc/.m2/repository/org/springframework/boot/spring-boot-starter/1.5.8.RELEASE/spring-boot-starter-1.5.8.RELEASE.jar:/Users/wdc/.m2/repository/org/springframework/boot/spring-boot/1.5.8.RELEASE/spring-boot-1.5.8.RELEASE.jar:/Users/wdc/.m2/repository/org/springframework/spring-context/4.3.12.RELEASE/spring-context-4.3.12.RELEASE.jar:/Users/wdc/.m2/repository/org/springframework/spring-aop/4.3.12.RELEASE/spring-aop-4.3.12.RELEASE.jar:/Users/wdc/.m2/repository/org/springframework/spring-beans/4.3.12.RELEASE/spring-beans-4.3.12.RELEASE.jar:/Users/wdc/.m2/repository/org/springframework/spring-expression/4.3.12.RELEASE/spring-expression-4.3.12.RELEASE.jar:/Users/wdc/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/1.5.8.RELEASE/spring-boot-autoconfigure-1.5.8.RELEASE.jar:/Users/wdc/.m2/repository/org/springframework/boot/spring-boot-starter-logging/1.5.8.RELEASE/spring-boot-starter-logging-1.5.8.RELEASE.jar:/Users/wdc/.m2/repository/ch/qos/logback/logback-classic/1.1.11/logback-classic-1.1.11.jar:/Users/wdc/.m2/repository/ch/qos/logback/logback-core/1.1.11/logback-core-1.1.11.jar:/Users/wdc/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar:/Users/wdc/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar:/Users/wdc/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.25/log4j-over-slf4j-1.7.25.jar:/Users/wdc/.m2/repository/org/springframework/spring-core/4.3.12.RELEASE/spring-core-4.3.12.RELEASE.jar:/Users/wdc/.m2/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar:/Users/wdc/.m2/repository/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar:/Users/wdc/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/Users/wdc/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.8.10/jackson-databind-2.8.10.jar:/Users/wdc/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.8.0/jackson-annotations-2.8.0.jar:/Users/wdc/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.10/jackson-core-2.8.10.jar:/Users/wdc/.m2/repository/org/springframework/boot/spring-boot-loader-tools/1.5.8.RELEASE/spring-boot-loader-tools-1.5.8.RELEASE.jar:/Users/wdc/.m2/repository/org/springframework/boot/spring-boot-starter-test/1.5.8.RELEASE/spring-boot-starter-test-1.5.8.RELEASE.jar:/Users/wdc/.m2/repository/org/springframework/boot/spring-boot-test/1.5.8.RELEASE/spring-boot-test-1.5.8.RELEASE.jar:/Users/wdc/.m2/repository/org/springframework/boot/spring-boot-test-autoconfigure/1.5.8.RELEASE/spring-boot-test-autoconfigure-1.5.8.RELEASE.jar:/Users/wdc/.m2/repository/com/jayway/jsonpath/json-path/2.2.0/json-path-2.2.0.jar:/Users/wdc/.m2/repository/net/minidev/json-smart/2.2.1/json-smart-2.2.1.jar:/Users/wdc/.m2/repository/net/minidev/accessors-smart/1.1/accessors-smart-1.1.jar:/Users/wdc/.m2/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar:/Users/wdc/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/wdc/.m2/repository/org/assertj/assertj-core/2.6.0/assertj-core-2.6.0.jar:/Users/wdc/.m2/repository/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar:/Users/wdc/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar:/Users/wdc/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/wdc/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar:/Users/wdc/.m2/repository/org/skyscreamer/jsonassert/1.4.0/jsonassert-1.4.0.jar:/Users/wdc/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar:/Users/wdc/.m2/repository/org/springframework/spring-test/4.3.12.RELEASE/spring-test-4.3.12.RELEASE.jar:/Users/wdc/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.9.0/jackson-dataformat-xml-2.9.0.jar:/Users/wdc/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.8.10/jackson-module-jaxb-annotations-2.8.10.jar:/Users/wdc/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar:/Users/wdc/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.jar:/Users/wdc/.m2/repository/org/apache/poi/poi-ooxml/3.17/poi-ooxml-3.17.jar:/Users/wdc/.m2/repository/org/apache/poi/poi/3.17/poi-3.17.jar:/Users/wdc/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/Users/wdc/.m2/repository/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar:/Users/wdc/.m2/repository/org/apache/poi/poi-ooxml-schemas/3.17/poi-ooxml-schemas-3.17.jar:/Users/wdc/.m2/repository/org/apache/xmlbeans/xmlbeans/2.6.0/xmlbeans-2.6.0.jar:/Users/wdc/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar:/Users/wdc/.m2/repository/com/github/virtuald/curvesapi/1.04/curvesapi-1.04.jar:/Users/wdc/.m2/repository/org/apache/commons/commons-csv/1.5/commons-csv-1.5.jar:/Users/wdc/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.57/bcpkix-jdk15on-1.57.jar:/Users/wdc/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.57/bcprov-jdk15on-1.57.jar:/Users/wdc/.m2/repository/com/hierynomus/sshj/0.23.0/sshj-0.23.0.jar:/Users/wdc/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/wdc/.m2/repository/com/jcraft/jzlib/1.1.3/jzlib-1.1.3.jar:/Users/wdc/.m2/repository/net/i2p/crypto/eddsa/0.2.0/eddsa-0.2.0.jar:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar" com.wdc.learnning.sftp.SftpUtil
objc[20678]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java (0x10b14f4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10c1c94e0). One of the two will be used. Which one is undefined.
Connected to the target VM, address: '127.0.0.1:55550', transport: 'socket'
16:33:41.428 [main] INFO net.schmizz.sshj.transport.random.BouncyCastleRandom - Generating random seed from SecureRandom.
16:33:41.432 [main] DEBUG net.schmizz.sshj.transport.random.BouncyCastleRandom - Creating random seed took 0 ms
16:33:41.772 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
16:33:41.772 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
16:33:41.772 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
16:33:41.772 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
16:33:41.774 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
16:33:41.783 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
16:33:41.783 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
16:33:41.783 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
16:33:41.783 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
16:33:41.792 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
16:33:41.793 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
16:33:41.793 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
16:33:41.794 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
16:33:41.795 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size
16:33:41.799 [main] WARN net.schmizz.sshj.DefaultConfig - Illegal key size or default parameters
16:33:41.799 [main] WARN net.schmizz.sshj.DefaultConfig - Disabling high-strength ciphers: cipher strengths apparently limited by JCE policy
16:33:41.799 [main] DEBUG net.schmizz.sshj.DefaultConfig - Available cipher factories: [aes128-cbc, aes128-ctr, blowfish-cbc, cast128-cbc, cast128-ctr, idea-cbc, idea-ctr, serpent128-cbc, serpent128-ctr, 3des-cbc, 3des-ctr, twofish128-cbc, twofish128-ctr, arcfour, arcfour128]
16:33:41.839 [main] DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve: nistp256, Key Len: 65, 0x04: 4
x: [-82, 4, 83, -119, 72, -86, -59, -46, -45, -11, -40, 61, -11, -52, -116, 60, 123, 29, 96, -77, 35, 27, 114, 105, -52, -31, 99, 64, -127, -84, -108, 89]
y: [109, 48, 1, 37, 1, 38, 107, -93, 102, 17, 68, -91, 64, 23, -66, 65, -47, 30, 115, 48, -43, -81, 63, -97, 101, 61, -66, -1, -7, -109, 70, -31]
16:33:42.032 [main] DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve: nistp256, Key Len: 65, 0x04: 4
x: [5, -95, 44, -15, 103, 72, -72, 108, -20, 33, 35, -17, 90, 19, -114, -34, -75, 31, 109, -82, -23, 87, -119, 68, -60, -53, -37, 0, -37, 90, 26, 27]
y: [-39, 126, 94, -57, -95, 78, 53, -40, 72, -66, -109, 53, 41, -61, 42, -116, 70, -99, 11, -58, 21, -35, 97, 13, -101, 28, -32, 112, -49, -64, -83, -74]
16:33:42.047 [main] INFO net.schmizz.sshj.transport.TransportImpl - Client identity string: SSH-2.0-SSHJ_0.23.0
16:33:42.080 [main] INFO net.schmizz.sshj.transport.TransportImpl - Server identity string: SSH-2.0-OpenSSH_7.6
16:33:42.080 [main] DEBUG net.schmizz.concurrent.Promise - Setting <<kex done>> to `null`
16:33:42.080 [main] DEBUG net.schmizz.sshj.transport.KeyExchanger - Sending SSH_MSG_KEXINIT
16:33:42.085 [main] DEBUG net.schmizz.concurrent.Promise - Setting <<kexinit sent>> to `SOME`
16:33:42.086 [main] DEBUG net.schmizz.concurrent.Promise - Awaiting <<kex done>>
16:33:42.090 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received SSH_MSG_KEXINIT
16:33:42.091 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Negotiated algorithms: [ kex=curve25519-sha256@libssh.org; sig=ecdsa-sha2-nistp256; c2sCipher=aes128-ctr; s2cCipher=aes128-ctr; c2sMAC=hmac-sha1; s2cMAC=hmac-sha1; c2sComp=none; s2cComp=none ]
16:33:42.105 [reader] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Sending SSH_MSG_KEXDH_INIT
16:33:42.111 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received kex followup data
16:33:42.111 [reader] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Received SSH_MSG_KEXDH_REPLY
16:33:42.111 [reader] DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve: nistp256, Key Len: 65, 0x04: 4
x: [-62, -73, 12, -107, -99, -98, 94, 64, 64, 38, -30, 121, -58, -42, 37, -35, -116, -36, 34, -98, 74, -55, 126, -119, -125, -27, -27, -110, -94, -3, 114, -72]
y: [59, 77, -33, -85, 126, -91, -17, -85, -97, 5, 58, 126, -123, -21, 5, 100, 29, -84, -99, 121, 120, -52, 55, -118, -105, 74, -16, 17, 3, -37, -91, 44]
16:33:42.152 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Trying to verify host key with net.schmizz.sshj.transport.verification.OpenSSHKnownHosts@7fa65c5a
16:33:42.153 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Trying to verify host key with net.schmizz.sshj.transport.verification.OpenSSHKnownHosts@5eb8b913
Disconnected from the target VM, address: '127.0.0.1:55550', transport: 'socket'
16:33:42.157 [reader] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `7a:cd:7f:11:a5:a1:fd:5f:1d:bd:8d:96:0e:37:46:06` for `localhost` on port 22
net.schmizz.sshj.transport.TransportException: Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `7a:cd:7f:11:a5:a1:fd:5f:1d:bd:8d:96:0e:37:46:06` for `localhost` on port 22
	at net.schmizz.sshj.transport.KeyExchanger.verifyHost(KeyExchanger.java:205)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:359)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)
16:33:42.158 [reader] INFO net.schmizz.sshj.transport.TransportImpl - Disconnected - HOST_KEY_NOT_VERIFIABLE
16:33:42.158 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Got notified of net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `7a:cd:7f:11:a5:a1:fd:5f:1d:bd:8d:96:0e:37:46:06` for `localhost` on port 22
16:33:42.158 [reader] DEBUG net.schmizz.sshj.transport.TransportImpl$NullService - Notified of net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `7a:cd:7f:11:a5:a1:fd:5f:1d:bd:8d:96:0e:37:46:06` for `localhost` on port 22
16:33:42.158 [reader] DEBUG net.schmizz.sshj.transport.TransportImpl - Setting active service to null-service
16:33:42.158 [main] ERROR net.schmizz.concurrent.Promise - <<kex done>> woke to: net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `7a:cd:7f:11:a5:a1:fd:5f:1d:bd:8d:96:0e:37:46:06` for `localhost` on port 22
16:33:42.158 [reader] DEBUG net.schmizz.sshj.transport.TransportImpl - Sending SSH_MSG_DISCONNECT: reason=[HOST_KEY_NOT_VERIFIABLE], msg=[Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `7a:cd:7f:11:a5:a1:fd:5f:1d:bd:8d:96:0e:37:46:06` for `localhost` on port 22]
16:33:42.159 [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<transport close>> to `SOME`
16:33:42.159 [reader] DEBUG net.schmizz.sshj.transport.Reader - Stopping
Exception in thread "main" net.schmizz.sshj.transport.TransportException: [HOST_KEY_NOT_VERIFIABLE] Could not verify `ecdsa-sha2-nistp256` host key with fingerprint `7a:cd:7f:11:a5:a1:fd:5f:1d:bd:8d:96:0e:37:46:06` for `localhost` on port 22
	at net.schmizz.sshj.transport.KeyExchanger.verifyHost(KeyExchanger.java:205)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:359)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:503)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:102)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:170)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:59)

Process finished with exit code 1

check about this log

**Comment by hierynomus** [comment]
High strength crypto indeed is not loaded. You might try to build from pr #396, where I did some work on the ecdsa-sha2-nistp keys.

**Comment by wdcwells** [comment]
ok thanks!! i'll try it later

**Comment by MetalCar** [comment]
I'm still struggeling with this bouncyCastle problem. Now i get the message:
Unable to reach a settlement: [] and [aes128-ctr, aes192-ctr, aes256-ctr, arcfour256, arcfour128, aes128-gcm@openssh.com, aes256-gcm@openssh.com, chacha20-poly1305@openssh.com, aes128-cbc, 3des-cbc, blowfish-cbc, cast128-cbc, aes192-cbc, aes256-cbc, arcfour, rijndael-cbc@lysator.liu.se]

**Comment by hierynomus** [comment]
Please load the high strength crypto extensions for java. There is no available algorithm locally that matches what the server supports.

**Comment by j0kkeri** [comment]
@MetalCar Have you tried putting the "bcprov-jdk15on-1.57.jar" in to JAVA_HOME\lib\ext ?

**Comment by MetalCar** [comment]
@j0kkeri Ya, i tried that. I found out, that the most of my problems are causing by the server where I try to connect to. Or rather, I'm giving up^^  So, i will solve that problem on an other way.

**Comment by AaliMohammed** [comment]
@MetalCar You might need to delete the bouncyCastle jar's and build the application. I was facing similar issue and the reason was bouncyCastle jar's being corrupted.
