### ISSUE TITLE
SCPFileTransfer doesn't support wildcard in file path?

### ISSUE THREAD

**Issue by ghost** [hierynomus/sshj#48]
version 0.6.1

This code works fine:
                `ssh.newSCPFileTransfer().download("/home/test.ini", "C:/test");`

But this doesn't work:
                `ssh.newSCPFileTransfer().download("/home/*.ini", "C:/test");`

Got error message:

```
02:22:31.190 [main] INFO  n.s.s.c.c.direct.SessionChannel - Will request to exec `scp -f -q -p -r '/home/*.ini'`
.......
Caused by: net.schmizz.sshj.xfer.scp.SCPException: Remote SCP command returned error: scp: /home/*.ini: No such file or directory
```

**Comment by impoldo1** [comment]
Could someone please reopen this issue?

The native scp command **does** support remote file globs (wildcards). For example the following would copy all files ending in ".conf" from the remote /etc directory to the current working directory on localhost:

`scp host:/etc/*.conf .`

This issue was unfortunately closed with an example that only showed that the scp command will treat '\*' as a literal character, not a wildcard. That is no surprise.

The original reporter was asking about using un-escaped wildcards in remote paths, when trying to download bunch of files at once from a remote host to the localhost, without having to iterate to a fixed list of (maybe not exactly known) remote file names.

It would be extremely useful if sshj could support the remote globs, too.  

Thanks  :)
