### ISSUE TITLE
Incorrect identification ending - missing carriage return

### ISSUE THREAD

**Issue by GalLuvton** [hierynomus/sshj#498]
I recently started noticing a warning I keep getting when connecting to my linux server:
```
(IdentificationStringParser.java:82) WARN  - Server identification has bad line ending, was expecting a '\r\n' however got: '1' (hex: 31)
(IdentificationStringParser.java:83) WARN  - Will treat the identification of this server 'SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u5-k1' leniently
```
After taking a look at the code, I noticed you are explicitly looking for a carriage return in the identification string ([here](https://github.com/hierynomus/sshj/blob/master/src/main/java/com/hierynomus/sshj/transport/IdentificationStringParser.java#L80)).
Is there a reason for this requirement? The linux server returns a proper string ending with a newline character, but no carriage return, as linux does not use those.
Is this part of the SSH protocol that I am missing?

**Comment by hierynomus** [comment]
Yes, that's the part you're missing, see the RFC here: https://tools.ietf.org/html/rfc4253#section-4.2

Section 4.2 specifies that:

> When the connection has been established, both sides MUST send an
   identification string.  This identification string MUST be

>      SSH-protoversion-softwareversion SP comments CR LF

>   Since the protocol being defined in this set of documents is version
   2.0, the 'protoversion' MUST be "2.0".  The 'comments' string is
   OPTIONAL.  If the 'comments' string is included, a 'space' character
   (denoted above as SP, ASCII 32) MUST separate the 'softwareversion'
   and 'comments' strings.  The identification MUST be terminated by a
   single Carriage Return (CR) and a single Line Feed (LF) character
   (ASCII 13 and 10, respectively).  Implementers who wish to maintain
   compatibility with older, undocumented versions of this protocol may
   want to process the identification string without expecting the
   presence of the carriage return character for reasons described in
   Section 5 of this document.  The null character MUST NOT be sent.
   The maximum length of the string is 255 characters, including the
   Carriage Return and Line Feed.

i.e. so in order to be compatible, we do not hard require the <CR> to be present, but do warn when it's missing.

**Comment by GalLuvton** [comment]
Thank you very much! I couldn't find it when googling. Closing
