### ISSUE TITLE
Adding support for chacha20-poly1305@openssh.com

### ISSUE THREAD

**Issue by xbankov** [hierynomus/sshj#629]
I suggest you add support for chacha20-poly1305@openssh.com cipher. It is one of the default ciphers in OpenSSH [https://man.openbsd.org/ssh_config.5#Ciphers](https://man.openbsd.org/ssh_config.5#Ciphers)

**Comment by bhoeckendorf** [comment]
As far as I understand, this cipher is very popular because it is both, strong and very performant. I'm using [tinyssh](https://github.com/janmojzis/tinyssh) inside containers. To keep the server footprint small, tinyssh supports only a minimal set of ciphers, in particular this one. Sadly, sshj (bundled with Jetbrains' IDEs) fail to connect to tinyssh because sshj doesn't support this cipher.
