### ISSUE TITLE
password less sudo user commands execution.

### ISSUE THREAD

**Issue by sivaprasadjava** [hierynomus/sshj#819]
Hi Team,

To establish the Session connection, I am using a regular username(siva) and password(siva).  once a session is created successfully, by using the same session I need to check out another sudo user 'oracle' to execute a command on Linux or Solaris, why is because this oracle user(passwordless access for this user) has those permissions to execute commands. here i  attached the sample code i am using now. but it is working in some cases only. sometimes commands are giving 1 as cmdExitStatus and the error stream throws an error message even though I allocated pty to the session properly. someone, please help me how to overcome this. 

my code
<img width="527" alt="image" src="https://user-images.githubusercontent.com/42302203/192048315-58324f91-062b-4e7f-b714-a39445d404d0.png">
below are the errors,
<img width="422" alt="image" src="https://user-images.githubusercontent.com/42302203/192044428-4d5f107b-99c0-4b8b-8ec5-75cd19f25f61.png">
<img width="934" alt="image" src="https://user-images.githubusercontent.com/42302203/192044361-091c5c07-31fb-4224-90ce-554ba80de52d.png">

Thanks,
Siva.

**Comment by DanWiseProgramming** [comment]
Hi Siva,
Does the `siva` user have a password for `sudo`?

**Comment by sivaprasadjava** [comment]
Hi @DanWiseProgramming, Yes Siva is a sudo user on the machine, need to connect with the sudo user siva/siva, and after that, I need to checkout to the Oracle user to execute a command. from sudo user to oracle we have a passwordless connection.

**Comment by DanWiseProgramming** [comment]
Yes, as I suspected @sivaprasadjava ,
When you run `sudo su - <targetuser>`, if the user you are running this command as doesn't have `NOPASSWD` configured in the `/etc/sudoers` file or there is no configuration fragment in `/etc/sudoers.d/`, then you will be prompted for a password. Not for `oracle`'s password but `siva`'s password since you are running `sudo` as the `siva` user, not `oracle`. Only once this command is successfully executed do you start running commands as the `oracle` user and no longer need a password for running `sudo` commands, as `oracle` most likely has `NOPASSWD` configured in the `sudoers` configuration.

As for the `tty`/no `-S` flag error, since you are establishing an SSH connection without a `tty` set up (as you would have with a physical console), SSH cannot prompt you to enter the password. Using `-S` as per the advice on-screen and piping the `siva` `sudo` password with `echo` would work to avoid needing a `tty`. This would work but is not recommended. A better approach could be to SSH in directly as `oracle` using an SSH public key-private key pair,

This is not an issue with SSHJ by any means, so this ticket should be closed in my opinion.

**Comment by sivaprasadjava** [comment]
Hi @hierynomus / @DanWiseProgramming ,

Many thanks for your time and efforts. I understand what you guys saying. 
When I flush the command and password by using Outputstream it's working as we expected. but the password also prints in the command output.
![image](https://github.com/hierynomus/sshj/assets/42302203/af12d46b-5059-4ab4-8da5-57b3084acc7a)

Thanks,
Siva.
