### ISSUE TITLE
CVE-2023-33201  BOUNCYCASTLE UP TO 1.73 SELF-SIGNED CERTIFICATE X509LDAPCERTSTORESPI.JAVA LDAP INJECTION

### ISSUE THREAD

**Issue by diyangsx** [hierynomus/sshj#873]
there is a vulnerability CVE-2023-33201.
```Summary[info](https://vuldb.com/?kb.cpe)[edit](https://vuldb.com/?edit.231726#software)
A vulnerability has been found in [bouncycastle up to 1.73](https://vuldb.com/?product.bouncycastle) and classified as 
problematic. Affected by this vulnerability is an unknown functionality of the file X509LDAPCertStoreSpi.java of the component 
Self-Signed Certificate Handler. The manipulation leads to ldap injection. This vulnerability is known as [CVE-2023-33201].
There is no exploit available. It is recommended to upgrade the affected component.

Details[info](https://vuldb.com/?kb.cpe)[edit](https://vuldb.com/?edit.231726#software)
A vulnerability, which was classified as problematic, was found in [bouncycastle up to 1.73]. Affected is an unknown code block of 
the file X509LDAPCertStoreSpi.java of the component Self-Signed Certificate Handler. The manipulation with an unknown input leads
 to a ldap injection vulnerability. CWE is classifying the issue as [CWE-90]. The software constructs all or part of an LDAP query 
using externally-influenced input from an upstream component, but it does not neutralize or incorrectly neutralizes special elements 
that could modify the intended LDAP query when it is sent to a downstream component. This is going to have an impact on integrity.

The weakness was released 06/16/2023. The advisory is available at [bugzilla.redhat.com](https://vuldb.com/?advisory_url.231726). 
This vulnerability is traded as [CVE-2023-33201] since 05/18/2023. Technical details are known, but there is no available exploit. 
This vulnerability is assigned to [T1505] by the MITRE ATT&CK project.

Upgrading to version 1.74 eliminates this vulnerability.
```

Does the vulnerability affect ssj?If there is any impact, please fix it as soon as possible.

**Comment by exceptionfactory** [comment]
SSHJ does not use the `X509LDAPCertStoreSpi` class, so this Bouncy Castle vulnerability should not be a concern for SSHJ. It is also possible to over the version of Bouncy Castle in a dependent project, which would avoid including the concerning version.

@hierynomus This raises an important question about ongoing support for Java 7 in SSHJ.

Bouncy Castle 1.72 changed the name of the library to have `jdk18on` instead of `jdk15on`, indicating Java 8 as a minimum required version. Bouncy Castle has released several other minor versions, and SLF4J 2.0 also requires Java 8. I would be glad to submit a pull request to update Bouncy Castle, but that would require making Java 8 the minimum version for SSHJ. What do you think?

**Comment by hierynomus** [comment]
Let's go for it! Java 7 is now so old.

Op do 29 jun. 2023 15:24 schreef exceptionfactory ***@***.***

**Comment by exceptionfactory** [comment]
> Let's go for it! Java 7 is now so old.

Thanks for the quick reply! I will work on putting together a pull request for the dependency upgrades and minimum Java version.

**Comment by diyangsx** [comment]
ok. Thank you for the reply. I know what to do with it.
